version = 0.1

[default.deploy.parameters]
stack_name = "github-profile-sam-dev"
resolve_s3 = true
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = [
  "ProjectName=github-profile-sam-dev",
  "DatabaseUrl=postgresql://postgres:YOUR_PASSWORD@database-1-instance-1.cziie46y84oa.us-east-2.rds.amazonaws.com:5432/database_japan",
  "JwtSecret=replace-with-at-least-32-characters",
  "CorsOrigin=http://localhost:3001",
  "VpcId=vpc-0b653a19dd83dfa79",
  "PrivateSubnetIds=subnet-0afbf279c7e89bd2d,subnet-0f1075ff3eaba752e",
  "AuroraSecurityGroupId=sg-0b4619fa07595e65f",
  "EnableCloudMapIntegration=false",
  "CloudMapNamespaceName=internal.github-profile",
  "GoServiceSecurityGroupId=",
  "EnableManagedVpcNetworking=false",
  "InternetGatewayId=igw-01db71fd0dd6333e6",
  "ManagedPublicSubnetCidr=172.31.240.0/24",
  "ManagedPrivateSubnet1Cidr=172.31.241.0/24",
  "ManagedPrivateSubnet2Cidr=172.31.242.0/24",
  "ManagedPublicSubnetAz=us-east-2a",
  "ManagedPrivateSubnet1Az=us-east-2b",
  "ManagedPrivateSubnet2Az=us-east-2c"
]
